# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 044e10f8f1397c666fee68bc30dfeb4b79010104e2a452535c5ceff1cfb8d54048ce98bf47d9bd312ffa4289672432c517ef90353ee6493899c214504eb4973e

test:
  secret_key_base: bc800259f059768eb02a6dfc5d3854cbbd6b0536a34acaae99efa8d88d2462ed9953077b65572a626eec540ffdd2669548f2746cc28803801d28dad7c439ad0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
